App_Tasks
Functions
void Command_Parser_Task (void *pvParameters)
void HouseKeeping_Task (void *pvParameters)
void PTTDecoder_Task (void *pvParameters)
void ADCSampler_Task (void *pvParameters)
void Idle_Task (void *pvParameters)
Dummy task created for checking if RTOS is alive. The task simple blink SF2 board LEDs.
Detailed Description
Application Tasks
Function Documentation
ADCSampler_Task()
void ADCSampler_Task (void * pvParameters)
ADCSampler_Task
This task is responsible for collecting ADC Sampler windows (2048 adc samples) and storing them into the ADC Sampler Buffer. The ADC Sampler is high priority task, it can not be preempted while collecting a ADC window to avoid losing samples. It runs on a infinite loop alternating between two states:
ADC_IDLE: the tasks suspends for 0,5s, allowing other tasks to run;
ADC_BUSY: the tasks collects 2048 samples from the ADC Sampler FIFO
             in the Decoder Unit and stores them into a ADC Sampler Package.
             After the reading is done the tasks automatically switches to
             ADC_IDLE state.
   When the task is in ADC_BUSY state it is not preempted,
   therefore other critical process, such as the PTT Decoding Task,
   must be suspended before the ADC Sampler switches to ADC_BUSY. To
   initiate an ADC window read operation the on-board computer must put the
   firmware into Configuration Mode and then send the ADC_LOAD command.
   The task will be ADC_BUSY state for roughly 16ms and then switch
   back to ADC_IDLE. The on-board computer must issue the
   ADC_STATE command to know when the ADC reading is finished.
ADCSampler_Task
It is responsible for collect ADC Sampler windows (2048 adc samples)
and storing them into the ADC Sampler Buffer. The ADC Sampler
is high priority task, it can not be preempted while collecting
a ADC window to avoid losing samples.
It runs on a infinite loop alternating between two states:
ADC_IDLE: the tasks suspends for 0,5s, allowing other tasks to run;
ADC_BUSY: the tasks collects 2048 samples from the ADC Sampler FIFO
            in the Decoder Unit and stores them into a ADC Sampler Package.
            After the reading is done the tasks automatically switches to
            ADC_IDLE state.
When the task is in ADC_BUSY state it is not preempted,
  therefore other critical process, such as the PTT Decoding Task,
  must be suspended before the ADC Sampler switches to ADC_BUSY. To
  initiate an ADC window read operation the on-board computer must put the
  firmware into Configuration Mode and then send the ADC_LOAD command.
  The task will be ADC_BUSY state for roughly 16ms and then switch
  back to ADC_IDLE. The on-board computer must issue the
  ADC_STATE command to know when the ADC reading is finished.
Definition at line 43 of file adc_task.c.
Referenced by sbcda_decoder_app().
Command_Parser_Task()
void Command_Parser_Task (void * pvParameters)
Command_Parser_Task
Task responsible for setting the current operation mode and its corresponding output package buffer. The Command Parser task is also responsible for executing configuration commands sent by the on-board computer. The result of each configuration command or request in configuration mode is a Configuration Data Package starting with the identifier byte 0x10. This task has low execution priority and can only run when the ADCSampler_Task and the PTTDecoder_Task are suspended. This behavior gives a small window of time for the on-board computer execute configuration commands or request HK information. Therefore, the on board computer must always check the type of a received data package (first byte) to be sure of which operation mode is currently set.
Command_Parser_Task
Definition at line 68 of file cmd_task.c.
References HK_Get_Buffer(), PTT_GetReadyFifoOutput(), and PTT_TOTAL_RECORD_SIZE.
Referenced by sbcda_decoder_app().
HouseKeeping_Task()
void HouseKeeping_Task (void * pvParameters)
HouseKeeping_Task
This task constantly reads housekeeping information and keeps an updated Housekeeping Package. The collected information are defined by the Housekeeping `configuration
  word.` The housekeeping information includes:
1 - RTC Current time tag; 2 - ADC 7894 current RMS value; 3 - Current sensors A and B updated values; 4 - PLL Synchronization flag; 5 - Over-current register flag;
The HK info is stored into a single HK Package, provided by the HK Service Layer. All Housekeeping measures are enabled by default. If the on-board computer deactivates one or more HK measures, their corresponding space is simply filled with zeros. The configuration word masks defines which HK measure is enabled or not. It can be updated by the on-board computer using the HK_CONFIG command with the firmware in Configuration Mode. The configuration word is a 2-byte integer whose bits are mapped as follows:
    0 - RTC time tag
    1 - Current sensors
    2 - ADC RMS
    3 - PLL Synch flag
    4 - Over - current
    5-15 - Reserved for future use
*
HouseKeeping_Task
This task constantly reads housekeeping information and keeps an updated Housekeeping Package. The collected information are defined by the Housekeeping `configuration
word.` The housekeeping information includes:
1 - RTC Current time tag; 2 - ADC 7894 current RMS value; 3 - Current sensors A and B updated values; 4 - PLL Synchronization flag; 5 - Over-current register flag;
The HK info is stored into a single HK Package, provided by the HK Service Layer. All Housekeeping measures are enabled by default. If the on-board computer deactivates one or more HK measures, their corresponding space is simply filled with zeros. The configuration word masks defines which HK measure is enabled or not. It can be updated by the on-board computer using the HK_CONFIG command with the firmware in Configuration Mode. The configuration word is a 2-byte integer whose bits are mapped as follows:
0 - RTC time tag 1 - Current sensors 2 - ADC RMS 3 - PLL Synch flag 4 - Over - current 5-15 - Reserved for future use
Definition at line 51 of file hkp_task.c.
References HK_Get_Buffer(), HK_Get_Config(), HK_Get_Refresh_Time(), and HK_Service_Setup().
Referenced by sbcda_decoder_app().
Idle_Task()
void Idle_Task (void * pvParameters)
Dummy task created for checking if RTOS is alive. The task simple blink SF2 board LEDs.
Idle_Task
Idle_Task
Dummy task created for checking if RTOS is alive
The task simple blink SF2 board LEDs.
This task is responsible for reloading the WDT
counter.
Definition at line 31 of file idle_task.c.
Referenced by sbcda_decoder_app().
PTTDecoder_Task()
void PTTDecoder_Task (void * pvParameters)
PTTDecoder_Task
The PTT Decoding task is responsible for coordinating the decoding process of newly detected PTT signals, as much as building PTT Packages. It rellies on services provided by the PTT Service and the DDS Layers. The PTT task runs in cycles of 10 ms, called windows. During each window the task performs the following activities:
  1. Run a Detection Loop to identify new PTT signals;
  2. Send a Decoding Start Operation signal if there are any active decoders;
  3. Run a Decoding Loop, procedure that adds new decoded bits to the currently building PTT Packages;
  4. Check if the firmware has received a PTT_POP command and, in this case, update the pointer of the PTT Packages FIFO ;
  5. Wait until the next window starts.
 Steps 1 to 3 are executed in high priority mode. The task cannot be preempted during these steps. Together they last about 4ms (40% of the window time). During the remaining time, the PTT task runs in low priority mode, allowing other tasks to control the processor. An interrupt signal is generated on GPIO_0 pin to trigger a new window. When this interruption is detected the system is forced to reenter the high priority state and restart the decoding process. The on-board computer can pause or resume the decoding process by using the PTT_PAUSE and PTT_RESUME commands in Configuration Mode. When the decoder is paused steps 1, 2 and 3 are not executed.
PTTDecoder_Task
Definition at line 39 of file ptt_task.c.
References DDS_clearNewWindowFlag(), DDS_Detection_Loop(), DDS_EnableDecoder(), DDS_isNewWindowReady(), DDS_Setup(), PTT_Service_isPaused(), and PTT_Service_Setup().
Referenced by sbcda_decoder_app().