PTT_Service
Macros
#define PTT_TOTAL_RECORD_SIZE 54
Enumerations
enum PTTDecode_Status {
PTT_FREE =0,
PTT_FRAME_SYNCH,
PTT_MESSAGE_LENGTH,
PTT_ID_NUMBER,
PTT_DATA,
PTT_ERROR,
PTT_READY
 }
Indicates the current decoding status of a PTT Package.
Functions
TaskHandle_t * PTT_GetTaskHandler (void)
void PTT_Service_Setup (void)
This function initializes the internal package buffer pointers and sets up the detection task.
void PTT_Service_Pause (void)
Pauses the detection task.
void PTT_Service_Resume (void)
Resumes the detection task.
uint8_t PTT_Service_isPaused (void)
Checks whether the detection task is paused or not.
void PTT_ResetPackage (PTTPackage_Typedef *ptr)
Resets a PTT Package to its PTT_FREE state.
PTTPackage_Typedef * PTT_PopFreePackage (void)
Returns the next free package from the free packages stack. If the stack is empty, returns a 0 pointer.
PTTPackage_Typedef * PTT_PopReadyPackage (void)
Returns the next free package from the free packages stack. If the stack is empty, returns a 0 pointer.
void PTT_PushReadyPackage (PTTPackage_Typedef *ptr)
Pushes a ready PTT Package into the PTT Ready FIFO.
uint16_t PTT_FreePackages_Available (void)
Returns the number of FREE PTT Packages available.
uint16_t PTT_ReadyPackages_Available (void)
Returns the number of PTT Records currently in the ready package buffer.
void PTT_SetPackageReadMutex ()
Used for indicating that a PTT_POP command was received.
void PTT_ClearPackageReadMutex ()
Used for indicating that a pending PTT_POP command handled.
uint8_t PTT_GetPackageReadMutex (void)
Returns the current state of the PackageReadMutex.
uint8_t * PTT_GetReadyFifoOutput (void)
Returns a pointer to the head of the PTT Ready packages FIFO.
void PTT_SetReadyFifoOutput (uint8_t *ptr)
Sets the current output FIFO pointer.
Detailed Description
Macro Definition Documentation
PTT_TOTAL_RECORD_SIZE
#define PTT_TOTAL_RECORD_SIZE 54
SBCDA Decoder instance description PTT Package parameters
Definition at line 28 of file ptt.h.
Referenced by Command_Parser_Task().
Enumeration Type Documentation
PTTDecode_Status
enum PTTDecode_Status
Indicates the current decoding status of a PTT Package.
PTTDecode_Status
Enumerator
PTT_FREE Package clean
PTT_FRAME_SYNCH Package is in Frame Synch phase.
PTT_MESSAGE_LENGTH Package is receiving the Message Length parameter bits.
PTT_ID_NUMBER Package is receiving the PTT ID Number parameter bits.
PTT_DATA Package is receiving the PCD Sensor data bits
PTT_ERROR Package failed the Fram Synch phase.
PTT_READY Package is is ready to be transmited to the on-board computer.
Definition at line 79 of file ptt.h.
Function Documentation
PTT_ClearPackageReadMutex()
void PTT_ClearPackageReadMutex ()
Used for indicating that a pending PTT_POP command handled.
PTT_ClearPackageReadMutex
When the PackageReadMutex is set the PTT Decoding task takes one PTT Ready package of the PTT Ready FIFO and updates its pointers. After updating the FIFO the PTT Decoding task resets the PackageReadMutex, allowing other PTT_POP commands to be executed.
Definition at line 126 of file ptt_service.c.
PTT_FreePackages_Available()
uint16_t PTT_FreePackages_Available (void)
Returns the number of FREE PTT Packages available.
PTT_FreePackages_Available
Returns
Number of free PTT Packages
Definition at line 260 of file ptt_service.c.
PTT_GetPackageReadMutex()
uint8_t PTT_GetPackageReadMutex (void)
Returns the current state of the PackageReadMutex.
PTT_GetPackageReadMutex
Returns
PackageReadMutex
Definition at line 130 of file ptt_service.c.
PTT_GetReadyFifoOutput()
uint8_t* PTT_GetReadyFifoOutput (void)
Returns a pointer to the head of the PTT Ready packages FIFO.
PTT_GetReadyFifoOutput
Returns
Ready PTT Package
Definition at line 134 of file ptt_service.c.
Referenced by Command_Parser_Task().
PTT_GetTaskHandler()
TaskHandle_t* PTT_GetTaskHandler (void)
 PTT SERVICE SPECIFIC FUNCTIONS
PTT_GetTaskHandler
Definition at line 87 of file ptt_service.c.
Referenced by sbcda_decoder_app().
PTT_PopFreePackage()
PTTPackage_Typedef* PTT_PopFreePackage (void)
Returns the next free package from the free packages stack. If the stack is empty, returns a 0 pointer.
PTT_PopFreePackage
Returns
Free PTT Package
PTT_GetNextFreePackage Returns the next free package from the free packages stack If the stack is empty, returns a 0 pointer
Definition at line 194 of file ptt_service.c.
PTT_PopReadyPackage()
PTTPackage_Typedef* PTT_PopReadyPackage (void)
Returns the next free package from the free packages stack. If the stack is empty, returns a 0 pointer.
PTT_PopReadyPackage
Returns
Ready PTT Package
PTT_GetNextFreePackage Returns the next free package from the free packages stack If the stack is empty, returns a 0 pointer
Definition at line 230 of file ptt_service.c.
References PTT_READY.
PTT_PushReadyPackage()
void PTT_PushReadyPackage (PTTPackage_Typedef * ptr)
Pushes a ready PTT Package into the PTT Ready FIFO.
PTT_PushReadyPackage
Parameters
ptr Pointer to the package to be pushed.
Definition at line 249 of file ptt_service.c.
PTT_ReadyPackages_Available()
uint16_t PTT_ReadyPackages_Available (void)
Returns the number of PTT Records currently in the ready package buffer.
PTT_ReadyPackages_Available
Returns
Number of ready PTT Packages
Definition at line 264 of file ptt_service.c.
PTT_ResetPackage()
void PTT_ResetPackage (PTTPackage_Typedef * ptr)
Resets a PTT Package to its PTT_FREE state.
PTT_ResetPackage
Definition at line 167 of file ptt_service.c.
References PTT_FREE.
PTT_Service_isPaused()
uint8_t PTT_Service_isPaused (void)
Checks whether the detection task is paused or not.
PTT_Service_isPaused
Returns
PTT Decoding task state
        0 - Task is running;
        1 - Task is Paused;
PTT_isPaused
Definition at line 164 of file ptt_service.c.
Referenced by PTTDecoder_Task().
PTT_Service_Pause()
void PTT_Service_Pause (void)
Pauses the detection task.
PTT_Service_Pause
Definition at line 150 of file ptt_service.c.
PTT_Service_Resume()
void PTT_Service_Resume (void)
Resumes the detection task.
PTT_Service_Resume
Definition at line 157 of file ptt_service.c.
PTT_Service_Setup()
void PTT_Service_Setup (void)
This function initializes the internal package buffer pointers and sets up the detection task.
PTT_Service_Setup
PTT_Service_Setup
This function initializes the internal buffer pointers
Definition at line 97 of file ptt_service.c.
Referenced by PTTDecoder_Task().
PTT_SetPackageReadMutex()
void PTT_SetPackageReadMutex ()
Used for indicating that a PTT_POP command was received.
PTT_SetPackageReadMutex
When the PackageReadMutex is set the PTT Decoding task takes one PTT Ready package of the PTT Ready FIFO and updates its pointers.
Definition at line 122 of file ptt_service.c.
PTT_SetReadyFifoOutput()
void PTT_SetReadyFifoOutput (uint8_t * ptr)
Sets the current output FIFO pointer.
PTT_SetReadyFifoOutput
Parameters
ptr Pointer to the next PTT READY package to be read by the on-board computer
Definition at line 144 of file ptt_service.c.