DDS
Macros
#define DDS_BASE 0x30000000
#define SBCDA_DECODER DDS_DECODER
Functions
DDS_Typedef * DDS_GetDecoderInstance (void)
void DDS_Setup (void)
uint8_t DDS_isNewWindowReady (void)
void DDS_clearNewWindowFlag (void)
void DDS_setNewWindowFlag (void)
void DDS_EnableDecoder (void)
void DDS_DisableDecoder (void)
void DDS_DecoderStartOp (void)
uint8_t DDS_DetectEop (void)
uint8_t DDS_DetectEmpty (void)
uint8_t DDS_DecoderEop (void)
uint8_t DDS_DecoderEmpty (void)
uint32_t DDS_ReadDetectBuffer (void)
void DDS_SetAmpThreshold (uint32_t val)
uint16_t DDS_CalcMessageLength (uint8_t msgLength)
uint8_t DDS_DecodeBit (uint16_t symb0, uint16_t symb1)
uint8_t DDS_Insert_Detected_Freq (uint32_t newIdx, uint32_t newAmp, uint8_t *assigned_decoder)
uint32_t DDS_Detection_Loop ()
void DDS_Update_Freq_Timeout (void)
uint32_t DDS_Decoding_Loop ()
Detailed Description
Macro Definition Documentation
DDS_BASE
#define DDS_BASE 0x30000000
Detect/Decoder bit masks
Definition at line 29 of file dds.h.
SBCDA_DECODER
#define SBCDA_DECODER DDS_DECODER
DDSDecoder regbank instance
Definition at line 164 of file dds.h.
Referenced by DDS_DecoderEmpty(), DDS_DecoderEop(), DDS_DecoderStartOp(), DDS_Decoding_Loop(), DDS_DetectEmpty(), DDS_DetectEop(), DDS_Detection_Loop(), DDS_DisableDecoder(), DDS_EnableDecoder(), DDS_GetDecoderInstance(), DDS_ReadDetectBuffer(), and DDS_SetAmpThreshold().
Function Documentation
DDS_CalcMessageLength()
uint16_t DDS_CalcMessageLength (uint8_t msgLength)
Returns the correspondent data portion size in bits for a given message length code. OBS: Assuming a 28bit ID_NUMBER format
Definition at line 242 of file dds.c.
DDS_clearNewWindowFlag()
void DDS_clearNewWindowFlag (void)
DDS_clearNewWindowFlag
Definition at line 75 of file dds.c.
Referenced by PTTDecoder_Task().
DDS_DecodeBit()
uint8_t DDS_DecodeBit (uint16_t symb0, uint16_t symb1)
Every symbol is a 10bit value in 2's complement format. However, they are placed into a 16bit unsigned int with no sign extension. This function sign extends the symbol values and then compare them in order to determine if they correspond to a 1 or a 0 bit. The following convention is assumed:
if symb0 <= symb1 => (-1) to (1) transition => bit 1 if symb0 > symb1 => (1) to (-1) transition => bit 0
Definition at line 287 of file dds.c.
DDS_DecoderEmpty()
uint8_t DDS_DecoderEmpty (void)
DDS_DecoderEmpty
A new detection is signalized when the DDS_DETECTOUT_BUFFER_EMPTY is clear
Definition at line 215 of file dds.c.
References SBCDA_DECODER.
Referenced by DDS_Decoding_Loop().
DDS_DecoderEop()
uint8_t DDS_DecoderEop (void)
DDS_DecoderEop
Definition at line 206 of file dds.c.
References SBCDA_DECODER.
Referenced by DDS_Decoding_Loop().
DDS_DecoderStartOp()
void DDS_DecoderStartOp (void)
DDS_DecoderStartOp()
Definition at line 179 of file dds.c.
References SBCDA_DECODER.
DDS_Decoding_Loop()
uint32_t DDS_Decoding_Loop ()
DDS_Decoding_Loop
The decoding loop is the procedure responsible for reading symbols out of the PTTD Buffer FIFO, converting them into bit representation and attaching each bit to its corresponding building package.
Returns
The number of finished packages in the current loop
fifo pop on this load
Definition at line 758 of file dds.c.
References DDS_DecoderEmpty(), DDS_DecoderEop(), and SBCDA_DECODER.
DDS_DetectEmpty()
uint8_t DDS_DetectEmpty (void)
DDS_DetectEmpty
A new detection is signalized when the DDS_DETECTOUT_BUFFER_EMPTY is clear
Definition at line 199 of file dds.c.
References SBCDA_DECODER.
Referenced by DDS_Detection_Loop().
DDS_DetectEop()
uint8_t DDS_DetectEop (void)
DDS_DetectEop
Definition at line 188 of file dds.c.
References SBCDA_DECODER.
Referenced by DDS_Detection_Loop().
DDS_Detection_Loop()
uint32_t DDS_Detection_Loop ()
DDS_Detection_Loop
The Detection Loop is responsible for acquiring new frequencies, assigning a free decoder to them and allocation a new PTT Package for the decoding process. It is also responsible for applying the software version of the Detection Mask for each new frequency, comparing them to the previously allocated ones.
Every new frequency is compared to the previously detected ones to avoid conflicts. A conflict happens when a new frequency is located less than 1.6 KHz (right or left) distant from any other frequency already assigned to a decoder. When a conflict occurs the system keeps the frequency associated to the highest amplitude, discarding the other. At the end of the Detection Loop the system is guaranteed to operate only with the highest components of the spectrum within the current 10ms window.
Returns
The number of newly detected frequencies during the current iteration
When previously assigned is replaced, it must leave space for the the new detected one. The previous decoding process must be stopped and its corresponding memory must be cleaned. The cleaning process will be performed during the Decoding_Loop when the package is marked as PTT_ERROR.
In this case the frequency was detected once and replaced another frequency that was also detected once. In the next iteration this frequency shall be 'detected_twice' and will be treated as a new detection.
Definition at line 669 of file dds.c.
References DDS_DetectEmpty(), DDS_DetectEop(), DDS_Update_Freq_Timeout(), and SBCDA_DECODER.
Referenced by PTTDecoder_Task().
DDS_DisableDecoder()
void DDS_DisableDecoder (void)
DDS_Disable_Decoder()
This function disables the detect/decoder module on FPGA Detection/decoding processes run only if ENABLE is set
Definition at line 172 of file dds.c.
References SBCDA_DECODER.
Referenced by DDS_Setup().
DDS_EnableDecoder()
void DDS_EnableDecoder (void)
DDS_Enable_Decoder_Module()
This function enables the detect/decoder module on FPGA Detection/decoding processes run only if ENABLE is set
Definition at line 160 of file dds.c.
References SBCDA_DECODER.
Referenced by PTTDecoder_Task().
DDS_GetDecoderInstance()
DDS_Typedef* DDS_GetDecoderInstance (void)
DDS_GetDecoderInstance
Definition at line 89 of file dds.c.
References SBCDA_DECODER.
DDS_Insert_Detected_Freq()
uint8_t DDS_Insert_Detected_Freq (uint32_t newIdx, uint32_t newAmp, uint8_t * assigned_decoder)
DDS_Insert_Detected_Freq
This procedure tries to insert a new detected freq/amp pair into the current frequencies vector. New frequencies must be at least 3.2KHz apart from previously allocated ones.
Parameters
new_idx = Newly detected frequency index.
new_amp = Newly detected frequency amp.
assigned_position = Number of the decoder assigned for the detected frequency
Returns
DDS_INSERT_FREQ_NEW: new frequency assigned to a free decoder position
DDS_INSERT_FREQ_REPLACE: new freq replace a previously assigned decoder
DDS_INSERT_FREQ_NONE: new freq could not be insterted because all decoders where busy.
Frequency idx have are 11 bits long with a precision of 128/2^11 kHz. The idx are signed and organized around zero (FFT result) and go from -1024 to +1023 (2^11) in 2's-complement format. However, after read the idx values are stored on 32bit unsigned integer variables, whithout sign extension.
Step resolution: 0,0625 kHz Overlap bandwidth: 3.2 kHz = 51.2 * 0,0625 kHz
Each new detected peak must be at least 51 freqIdxes apart (left and right)
Definition at line 499 of file dds.c.
DDS_isNewWindowReady()
uint8_t DDS_isNewWindowReady (void)
DDS_isNewWindowReady
Definition at line 68 of file dds.c.
Referenced by PTTDecoder_Task().
DDS_ReadDetectBuffer()
uint32_t DDS_ReadDetectBuffer (void)
DDS_POP_DetectBuffer
This function performs a READ operation on the detection data buffer. Each READ pops one element of the data fifo, updating the control register
Definition at line 226 of file dds.c.
References SBCDA_DECODER.
DDS_SetAmpThreshold()
void DDS_SetAmpThreshold (uint32_t val)
DDS_SetAmpThreshold
Definition at line 233 of file dds.c.
References SBCDA_DECODER.
DDS_setNewWindowFlag()
void DDS_setNewWindowFlag (void)
DDS_setrNewWindowFlag
Definition at line 82 of file dds.c.
DDS_Setup()
void DDS_Setup (void)
DDS_Driver_Init DDS_Setup This function must be called before the detection/decoding process starts, in order to initialize the detection driver internal variables correctly.
DDS_Setup
Definition at line 35 of file dds.c.
References DDS_DisableDecoder().
Referenced by PTTDecoder_Task().
DDS_Update_Freq_Timeout()
void DDS_Update_Freq_Timeout (void)
DDS_Update_Freq_Timeout When previously assigned is replaced, it must leave space for the the new detected one. The previous decoding process must be stopped and its corresponding memory must be cleaned. The cleaning process will be performed during the Decoding_Loop when the package is marked as PTT_ERROR.
Definition at line 612 of file dds.c.
Referenced by DDS_Detection_Loop().