SBCDA_APP
Modules
ADCSampler
App_Tasks
HW_Setup
DDS
HK_Service
PTT_Service
RTC_Service
Functions
void sbcda_decoder_app (void)
Detailed Description
Function Documentation
sbcda_decoder_app()
void sbcda_decoder_app (void)
sbcda_decoder_app
Definition at line 31 of file sbcda_decoder_app.c.
References ADCSampler_Task(), Command_Parser_Task(), HouseKeeping_Task(), Idle_Task(), PTT_GetTaskHandler(), PTTDecoder_Task(), and tskIDLE_PRIORITY.