Housekeeping_Service
Data Structures
struct HKPackage_Typedef
Defines the default format for HouseKeeping packages.
Functions
void HK_Service_Setup ()
Initializes Housekeeping service.
uint8_t * HK_Get_Buffer ()
Returns a pointer to the HK Package.
void HK_Set_Config (uint16_t word)
Sets the current HK config word.
uint16_t HK_Get_Config ()
Returns the current HK configuration word.
void HK_Set_Refresh_Time (uint8_t t)
Sets the refresh time for collecting HK information.
uint8_t HK_Get_Refresh_Time ()
Returns the current refresh time of the HK Task in ms.
Detailed Description
Function Documentation
HK_Get_Buffer()
uint8_t* HK_Get_Buffer ()
Returns a pointer to the HK Package.
HK_Get_Buffer
Returns
(uint8_t *) A pointer to the latest HK Package
Definition at line 97 of file housekeeping_service.c.
Referenced by HouseKeeping_Task().
HK_Get_Config()
uint16_t HK_Get_Config ()
Returns the current HK configuration word.
HK_Get_Config
Returns
Current HK config word
Definition at line 69 of file housekeeping_service.c.
HK_Get_Refresh_Time()
uint8_t HK_Get_Refresh_Time ()
Returns the current refresh time of the HK Task in ms.
HK_Set_Refresh_Time
Returns
refresh time in ms.
Definition at line 87 of file housekeeping_service.c.
Referenced by HouseKeeping_Task().
HK_Service_Setup()
void HK_Service_Setup ()
Initializes Housekeeping service.
HK_Service_Setup
Definition at line 44 of file housekeeping_service.c.
Referenced by HouseKeeping_Task().
HK_Set_Config()
void HK_Set_Config (uint16_t word)
Sets the current HK config word.
HK_Set_Config
The configuration word masks defines which HK measure is enabled or not. It can be updated by the on-board computer using the HK_CONFIG command with the firmware in Configuration Mode. The configuration word is a 2-byte integer whose bits are mapped as follows:
0 - RTC time tag
1 - Current sensors
2 - ADC RMS
3 - PLL Synch flag
4 - Over - current
5-15 - Reserved for future use
Parameters
word HK configuration word.
Definition at line 60 of file housekeeping_service.c.
HK_Set_Refresh_Time()
void HK_Set_Refresh_Time (uint8_t t)
Sets the refresh time for collecting HK information.
HK_Set_Refresh_Time
Parameters
t Refresh time in ms.
Definition at line 78 of file housekeeping_service.c.